postgres:
  image: postgres:9.5
  environment:
    - POSTGRES_USER=cog
    - POSTGRES_PASSWORD=cog

cog:
  image: operable/cog:0.8
  environment:
    - DATABASE_URL=ecto://cog:cog@localhost:5432/cog
    - COG_ADAPTER=slack
    - SLACK_API_TOKEN=${SLACK_API_TOKEN}
    - COG_MQTT_HOST=0.0.0.0
    - COG_API_URL_HOST=${COG_HOST}
    - COG_API_URL_PORT=80
    - COG_TRIGGER_URL_HOST=${COG_HOST}
    - COG_TRIGGER_URL_PORT=4001
    - COG_SERVICE_URL_HOST=${COG_HOST}
    - COG_SERVICE_URL_PORT=4002
    - RELAY_ID=00000000-0000-0000-0000-000000000000
    - RELAY_COG_TOKEN=supersecret
  links:
    - postgres:localhost
  ports:
    - 1883
    - 80:4000
    - 4001:4001
    - 4002:4002
  entrypoint: /home/operable/cog/scripts/docker-start

relay:
  image: operable/relay:0.8
  privileged: true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - RELAY_ID=00000000-0000-0000-0000-000000000000
    - RELAY_COG_TOKEN=supersecret
    - RELAY_COG_REFRESH_INTERVAL=30s
    - RELAY_DOCKER_CLEAN_INTERVAL=1m
    - RELAY_COG_HOST=localhost
    - RELAY_DYNAMIC_CONFIG_ROOT=/tmp/bundle_configs
  links:
    - cog:localhost
  entrypoint: /usr/local/bin/relay
